baseURL = "https://alexohneander.de"
title = "Alexohneander"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "JSON" ]

[params]
env = "production"
title = "Alexohneander"
description = "I'm Alex, DevOps/Network architect and software developer. I'm currently working on deineApotheke and Amamed."
keywords = [ "Blog", "Portfolio", "Kubernetes", "Software", "DevOps", "Network", "Architekt", "Entwickler", "Apotheke", "Amamed" ]
author = "Alex Wellnitz"
# images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Alexohneander"
#   icon = "/apple-touch-icon.png"
  iconHeight = 35

  # [params.profileMode]
  # enabled = false
  # title = "ExampleSite"
  # subtitle = "This is subtitle"
  # imageUrl = "<img location>"
  # imageWidth = 120
  # imageHeight = 120
  # imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Moin 👋"
  Content = "I'm Alex, DevOps/Network architect and software developer. I'm currently working on deineApotheke and Amamed. I help developers build a faster web and teach about web development, Kubernetes, network security and more.\n\n"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:moin@wellnitz-alex.de"

  [[params.socialIcons]]
  name = "xing"
  url = "https://www.xing.com/profile/Alex_Wellnitz/"

  [[params.socialIcons]]
  name = "dev"
  url = "https://dev.to/n00d13"
  
  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.dev-null.rocks/@alexohneander"
  rel = "me"

  [[params.socialIcons]]
  name = "hackthebox"
  url = "https://app.hackthebox.com/profile/29665"
  
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/alexohneander"



# [params.analytics.google]
# SiteVerificationTag = "XYZabc"

# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"

# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/alexohneander/alexohneander-hugo/tree/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "index"
name = "Über Mich"
url = "/"
weight = 10

[[menu.main]]
identifier = "experience"
name = "Erfahrung"
url = "/experience/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Suche"
url = "/search/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[module]
[[module.mounts]]
  source = 'assets'
  target = 'assets'
